### ISSUE TITLE
错误处理异常

### ISSUE THREAD

**Issue by Kxuan** [tengattack/certbot-dns-dnspod#7]
https://github.com/tengattack/certbot-dns-dnspod/blob/70833e54c2e2f7a40cc722fd260952ea00006339/certbot_dns_dnspod/dns_dnspod.py#L126

dnspod的API返回了中文错误。导致这里判断出错了。
可能需要或一下判断

参考返回
```
域名不正确，请输入主域名，如 dnspod.cn
```

**Comment by tengattack** [comment]
咦，之前是英文错误的吗？是 DNSPod 改了吗

**Comment by Kxuan** [comment]
> 咦，之前是英文错误的吗？是 DNSPod 改了吗

不知道……昨天刚搞了个新域名，用这个直接挂了……

**Comment by tengattack** [comment]
看了下逻辑这个错误应该是正常走到下面 `errors.PluginError` 的，然后会正常继续继续检测下一个域名，直到找到主域名才对，晚点我试试

**Comment by tengattack** [comment]
已修复 https://github.com/tengattack/certbot-dns-dnspod/commit/fc995c29397b38a22fa390ed1befb56195e54b25
